package reliable_test

import (
	"compress/gzip"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"strings"
	"testing"

	reliable "github.com/mas-bandwidth/reliable.go"
)

// This file is the Go side of the wire compatibility check. generateTranscript
// implements exactly the same deterministic scenario as interop/transcript.c,
// and TestWireCompatibility verifies that it reproduces, byte for byte, the
// golden transcript generated by the C library (pinned by the commit in
// interop/regenerate.sh). Keep the two implementations of the scenario in
// sync, and regenerate the golden whenever the scenario changes.

const wireMaxPacketBytes = 4096
const wireNumIterations = 300

func wireGeneratePacketData(sequence uint16, packetData []byte) []byte {
	packetBytes := (int(sequence)*1023)%(wireMaxPacketBytes-2) + 2
	packetData[0] = byte(sequence & 0xFF)
	packetData[1] = byte((sequence >> 8) & 0xFF)
	for i := 2; i < packetBytes; i++ {
		packetData[i] = byte((i + int(sequence)) % 256)
	}
	return packetData[:packetBytes]
}

func generateTranscript() string {
	var b strings.Builder

	var sender, receiver *reliable.Endpoint

	transmitCount := 0

	transmit := func(id uint64, sequence uint16, packetData []byte) {
		transmitCount++

		fmt.Fprintf(&b, "T %d %d %s\n", id, sequence, hex.EncodeToString(packetData))

		// deterministic packet loss

		if transmitCount%5 == 0 {
			return
		}

		destination := receiver
		if id == 1 {
			destination = sender
		}

		destination.ReceivePacket(packetData)

		// deterministic duplication

		if transmitCount%11 == 0 {
			destination.ReceivePacket(packetData)
		}
	}

	process := func(id uint64, sequence uint16, packetData []byte) bool {
		return true
	}

	printAcks := func(endpoint *reliable.Endpoint, id int) {
		fmt.Fprintf(&b, "A %d", id)
		for _, ack := range endpoint.Acks() {
			fmt.Fprintf(&b, " %d", ack)
		}
		fmt.Fprintf(&b, "\n")
	}

	time := 100.0

	senderConfig := reliable.DefaultConfig()
	receiverConfig := reliable.DefaultConfig()

	senderConfig.FragmentAbove = 500
	receiverConfig.FragmentAbove = 500

	senderConfig.Name = "sender"
	senderConfig.ID = 0
	senderConfig.TransmitPacketFunction = transmit
	senderConfig.ProcessPacketFunction = process

	receiverConfig.Name = "receiver"
	receiverConfig.ID = 1
	receiverConfig.TransmitPacketFunction = transmit
	receiverConfig.ProcessPacketFunction = process

	var err error
	sender, err = reliable.NewEndpoint(&senderConfig, time)
	if err != nil {
		panic(err)
	}
	receiver, err = reliable.NewEndpoint(&receiverConfig, time)
	if err != nil {
		panic(err)
	}

	packetData := make([]byte, wireMaxPacketBytes)

	for range wireNumIterations {
		packet := wireGeneratePacketData(sender.NextPacketSequence(), packetData)
		sender.SendPacket(packet)

		packet = wireGeneratePacketData(receiver.NextPacketSequence(), packetData)
		receiver.SendPacket(packet)

		sender.Update(time)
		receiver.Update(time)

		printAcks(sender, 0)
		printAcks(receiver, 1)

		sender.ClearAcks()
		receiver.ClearAcks()

		time += 0.01
	}

	senderCounters := sender.Counters()
	receiverCounters := receiver.Counters()

	for i := range reliable.NumCounters {
		fmt.Fprintf(&b, "C 0 %d %d\n", i, senderCounters[i])
	}
	for i := range reliable.NumCounters {
		fmt.Fprintf(&b, "C 1 %d %d\n", i, receiverCounters[i])
	}

	return b.String()
}

// TestWireCompatibility verifies that the Go port is binary compatible with
// the C reliable library: every transmitted packet, ack and counter in the
// deterministic scenario must match the golden transcript generated by the C
// implementation exactly.
func TestWireCompatibility(t *testing.T) {
	file, err := os.Open("testdata/c_transcript.txt.gz")
	if err != nil {
		t.Fatalf("could not open golden transcript (run interop/regenerate.sh): %v", err)
	}
	defer file.Close()

	reader, err := gzip.NewReader(file)
	if err != nil {
		t.Fatalf("could not read golden transcript: %v", err)
	}
	defer reader.Close()

	wantBytes, err := io.ReadAll(reader)
	if err != nil {
		t.Fatalf("could not read golden transcript: %v", err)
	}
	want := string(wantBytes)

	got := generateTranscript()

	if got == want {
		return
	}

	wantLines := strings.Split(want, "\n")
	gotLines := strings.Split(got, "\n")
	for i := 0; i < len(wantLines) && i < len(gotLines); i++ {
		if wantLines[i] != gotLines[i] {
			t.Fatalf("wire transcript diverges from the C library at line %d:\n c: %.120s\ngo: %.120s", i+1, wantLines[i], gotLines[i])
		}
	}
	t.Fatalf("wire transcript line count differs from the C library: c %d lines, go %d lines", len(wantLines), len(gotLines))
}
